services:
  bpqapi:
    image: m0lte/bpqapi
    ports:
      - 8080:8080
    environment:
      - bpq__uri=http://host.docker.internal:8008
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
  imapapi:
    image: ghcr.io/packethacking/bpq-imap-bulletins:main
    ports:
      - 143:2143
    environment:
      - bpqapi=bpqapi
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  roundcube:
    image: roundcube/roundcubemail
    ports:
      - 8000:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=imapapi
      - ROUNDCUBEMAIL_SMTP_SERVER=host.docker.internal
      - ROUNDCUBEMAIL_DEFAULT_PORT=2143
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
  bpqmon:
    image: ghcr.io/packethacking/bpqmonmqtt:main
    environment:
      - BPQMON_MQTT_HOSTNAME=mosquitto
      - BPQMON_MQTT_PORT=1883
      - BPQMON_MQTT_USERNAME=bpqmon
      - BPQMON_MQTT_PASSWORD=bpqmon
    restart: unless-stopped
    tty: true
  bpqmonweb:
    image: ghcr.io/packethacking/bpqmonweb:main
    ports:
      - 8081:80
    restart: unless-stopped
